id = "emmylua"
name = "EmmyLua"
description = "EmmyLua support."
version = "0.0.1"
schema_version = 1
authors = ["0x2CA <2478557459@qq.com>"]
repository = "https://github.com/CppCXY/Zed-EmmyLua"

[language_servers.emmylua]
name = "EmmyLua"
languages = ["EmmyLua", "Lua"]

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "a24dab177e58c9c6832f96b9a73102a0cfbced4a"
